```{r}
df8<-read.csv("df8.csv")
```


```{r}
#bar plot for age vs outcome
age <- table(df8$Outcome,df8$Age.Group)
barplot(age, main="Age and COVID Cases",
        xlab="Age Group", col=c("lightblue","pink"),
        legend = rownames(age), beside=TRUE)
```


```{r}
#bar plot for outbreak vs outcome
out <- table(df8$Outcome,df8$Outbreak.Associated)
barplot(out, main="Outbreak Type and COVID Cases",
        xlab="Outbreak Type", ylab="Frequency", col=c("lightblue","pink"),
        legend = rownames(out), beside=TRUE)
```


```{r}
#bar plot for source vs outcome
sou <- table(df8$Outcome,df8$Source.of.Infection)
barplot(sou, main="Source of Infection and COVID Cases",
        xlab="Source of Infection", col=c("lightblue","pink"),
        legend = rownames(sou), beside=TRUE)

```

```{r}
#bar plot for gender vs outcome
gen <- table(df8$Outcome,df8$Client.Gender)
barplot(gen, main="Gender and COVID Cases",
        xlab="Gender", col=c("lightblue","pink"),
        legend = rownames(gen), beside=TRUE)
```


```{r}
#bar plot for hospitalization vs outcome
hou <- table(df8$Outcome,df8$Ever.Hospitalized)
barplot(hou, main="Hospitalization Status and COVID Cases",
        xlab="Hospitalization Status", col=c("lightblue","pink"),
        legend = rownames(hou), beside=TRUE)
```


```{r}
#bar plot for ICU vs outcome
icu <- table(df8$Outcome,df8$Ever.in.ICU)
barplot(icu, main="ICU Status and COVID Cases",
        xlab="ICU Status", col=c("lightblue","pink"),
        legend = rownames(icu), beside=TRUE)
```


```{r}
#bar plot for Intubation vs outcome
int <- table(df8$Outcome,df8$Ever.Intubated)
barplot(int, main="Intubation Status and COVID Cases",
        xlab="Intubation Status", col=c("lightblue","pink"),
        legend = rownames(int), beside=TRUE)
```


```{r}
#Bar plot for Month
df8$Month <- as.factor(df8$Month)
mon <- table(df8$Outcome,df8$Month)
barplot(mon, main="Month and COVID Cases",
        xlab="Months", col=c("lightblue","pink"),
        legend = rownames(mon), beside=FALSE)
```


```{r}
#boxplot for income
boxplot(df8$Income,main="boxplot of Income")
```

```{r}
#log transform 
loginc <- log(as.data.frame(df8$Income))
boxplot(loginc, main="Log-transformed boxplot of Income")
```


```{r}
#boxplot for onset date
boxplot(df8$Onset.Report,main="boxplot of days from onset to report")
boxplot(log(df8$Onset.Report), main="log-transformed boxplot of days from onset to report")
```



