---
word_document: default
output: word_document
---


```{r}
#Load Data
df3<-read.csv("df3.csv")
str(df3)
#prepare data
df6 <- df3

df6$Income <- log(df3$Income)
df6$Density <- log(df3$Density)
col1 <- c("Outbreak.Associated","Age.Group","Source.of.Infection","Client.Gender", "Outcome","Ever.Hospitalized","Ever.in.ICU","Ever.Intubated","Month")
df6[col1] <-lapply(df6[col1],factor)
df6$Outcome <- ifelse(df6$Outcome == "RESOLVED", 1,0)

write.csv(df6,"C:/KZ/S/CIND820\\df6.csv", row.names = FALSE)

#Prepare test-train data
str(df6)
set.seed(123)
train_index1 <- sample(1:nrow(df6), 0.7 * nrow(df6))
train1 <- df6[train_index1,]
test1 <- df6[-train_index1,]

```


```{r}
#Data imbalanced
table(train1$Outcome)
```

```{r}
#GLM model
glm <- glm(Outcome~.,data=train1, family = "binomial")
summary(glm)
```

```{r}
predictglm <- predict(glm, test1, type="response")
```


```{r}
# prediction for glm
predictnum <- ifelse(predictglm >= 0.5,1,0) 

#Confusion matrix for glm
library(caret)
confusionMatrix(as.factor(test1$Outcome), as.factor(predictnum))
```


```{r}
#ROC curve
library(pROC)
lm=roc(test1$Outcome, predictnum) #AUC score
plot(lm ,main ="ROC curve -- Logistic Regression ",print.auc=TRUE)
```
```{r}
#Decision tree
library(rpart.plot)
```

```{r}
tree <- rpart(Outcome~., data = train1, method = 'class')
rpart.plot(tree)
```

```{r}
#Prediction for decision tree
treepred <-predict(tree, test1, type = 'class')

```

```{r}
#Confusion matrix for decision tree
confusionMatrix(as.factor(test1$Outcome), as.factor(treepred))
```

```{r}
#ROC curve for decision tree
roctree <-roc(test1$Outcome, as.numeric(treepred)) #AUC score
plot.roc(roctree,main ="ROC curve -- Decision Tree ",print.auc=TRUE)
```

```{r}
#prepare for XGBoost
library(fastDummies)
train1new<-dummy_cols(train1)
train1new <-subset(train1new[9:52])
test1new <-dummy_cols(test1)
test1new <-subset(test1new[9:52])
```

```{r}
#set up XGBoost
params <- list(eta = 0.3,
               set.seed = 123, 
               max_depth = 6,
               scale_pos_weight = 70,
               eval_metric = "auc",
               objective = "binary:logistic")
library(xgboost)


x_train = as.matrix(train1new[,-3])
y_train = train1new$Outcome
x_test = data.matrix(test1new[,-3])
y_test = test1new$Outcome
xgboost_train = xgb.DMatrix(data=x_train,label=y_train)
xgboost_test = xgb.DMatrix(data=x_test,label=y_test)
```

```{r}
#Model XGBoost
model <- xgboost(data = xgboost_train,
                 nrounds = 20, max_depth= 6, objective = "binary:logistic", eval_metric = "auc", nthread = 4,booster="gbtree")
```

```{r}
#Prediction for XGBoost
xgpred <- predict(model, xgboost_test)
xgnum <- ifelse(xgpred >= 0.5,1,0) 
```

```{r}
#Confusion matrix for XGBoost
confusionMatrix(as.factor(test1new$Outcome),as.factor(xgnum))
```

```{r}
#ROC curve for XGBoost
rocxg=roc(y_test , xgnum) #AUC score
plot(rocxg ,main ="ROC curve -- XGBoost ",print.auc=TRUE)
```









